---

- name: VECTOR CONFIGURE | Configure
  template:
    src: etc/vector/vector.toml.j2
    dest: /etc/vector/vector.toml
    owner: root
    group: root
    mode: 0644

- name: VECTOR CONFIGURE | Test configuration file
  command: vector test /etc/vector/vector.toml
  notify: Restart vector
